language: objective-c

branches:
  only:
    - master

xcode_project: Tactile.xcodeproj
xcode_scheme: TactileTests
osx_image: xcode8
xcode_sdk: iphonesimulator10.0

script:
  - xcodebuild test -project Tactile.xcodeproj -scheme TactileTests -destination "platform=iOS Simulator,name=iPhone 6s"
